{{ $name := include "rest-api.name" . }}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ $name }}
  labels: {{ include "rest-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "rest-api.selectorLabels" . | nindent 6 }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels: {{ include "rest-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ $name }}-container
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.port | int }}
        resources:
            limits:
              cpu: "250m"
              memory: "128M"


            