apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "persistent-layer.name" . | printf "%s-network-policy" }}
spec:
  podSelector:
    matchLabels: {{ include "persistent-layer.selectorLabels" .  | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels: 
          access: rest-api 
  egress:
  - to:
    - podSelector:
        matchLabels:
          access: rest-api
  policyTypes:
  - Ingress
  - Egress