stages:
  - upload
    
upload:
  stage: upload
  image: google/cloud-sdk:alpine
  services:
    - docker:dind
    - alpine/helm:latest
  script:
    - echo "Packaging chart:"
    - helm package . -d ./out
    - echo "Pushing to Artifact Registry"
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json 
    - cat gcloud-service-key.json | helm registry login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
    - helm push ./out/strapi-0.1.0.tgz oci://us-central1-docker.pkg.dev/