stages:
  - upload
    
upload:
  stage: upload
  image: 
    name: alpine/helm
    entrypoint: ["/bin/sh", "-c"]
  services:
    - google/cloud-sdk:alpine
  script:
    - echo "Packaging chart:"
    - helm package . -d ./out
    - echo "Authenticating Helm"
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json 
    - cat gcloud-service-key.json | helm registry login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
    - echo "Pushing to Artifact Registry"
    - helm push ./out/strapi-0.1.0.tgz oci://us-central1-docker.pkg.dev/$GCP_PROJECT_ID/sc-helm
    - echo "Authenticating gcloud"
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID