stages:
  - upload
    
upload:
  stage: upload
  image: google/cloud-sdk:alpine
  services:
    - docker:dind
    - alpine/helm:latest
  script:
    - echo "Packaging chart:"
    - helm package . -d ./out
    - echo "Pushing to Artifact Registry"
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json 
    - cat gcloud-service-key.json | helm registry login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
    - alias helm="docker run -ti --rm -v $(pwd):/apps -w /apps \
      -v ~/.kube:/root/.kube -v ~/.helm:/root/.helm -v ~/.config/helm:/root/.config/helm \
      -v ~/.cache/helm:/root/.cache/helm \
      alpine/helm"
    - helm push ./out/strapi-0.1.0.tgz oci://us-central1-docker.pkg.dev/