stages:
  - package
  - upload

package:
  stage: package
  image: alpine/helm:latest
  script:
    - echo "Packaging chart:"
    - helm package . -d ./out
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - ./out
    
upload:
  stage: upload
  image: google/cloud-sdk:alpine
  dependencies:
    - package
  services:
    - docker:dind
  script:
    - echo "Pushing to Artifact Registry"
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json 
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - cat gcloud-service-key.json | helm registry login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
    - gcloud config set project $GCP_PROJECT_ID
    - helm push ./out/strapi-0.1.1.tgz oci://us-central1-docker.pkg.dev/