apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web-ui.name" . | printf "%s-ingress" }}
spec:
  defaultBackend:
    service:
      name: {{ include "web-ui.name" . | printf "%s-service"}}
      port:
        number: {{ .Values.port | default 3000 }}