{{ $name := include "web-ui.name" . }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name | printf "%s-network-policy" }}
spec:
  podSelector:
    matchLabels: 
      access: web-ui
  ingress: []
  egress: []
  policyTypes:
  - Ingress
  - Egress