# Default values for persistent-layer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: {}

image:
  repository: postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "alpine"

port: 5432

deployment:
  replicaCount: 1
  mountPath: /var/lib/postgresql/data 

service:
  type: NodePort
  nodePort: 30001

persistentVolume:
  storage: 1Gi
  storageRequest: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/postgres/data
  storageClassName: microk8s-hostpath