# Default values for persistent-layer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "alpine"

statefulSet:
  containerPort: 5432 

service:
  type: ClusterIP
  port: 80

persistentVolume:
  storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path:  "/opt/postgres/data"
  storageClassName: microk8s-hostpath 