apiVersion: v1
kind: PersistentVolume
metadata: 
  name: {{printf "%s-pv-volume" ( include "persistent-layer.name" . )}} 
  labels: {{ include "persistent-layer.labels" . | nindent 4 }}
    type: local
spec: 
  storageClassName: {{ .Values.persistentVolume.storageClassName | default "microk8s-hostpath"}}
  capacity: 
    storage: {{ .Values.persistentVolume.storage | default "5Gi" }} 
  accessModes: 
  {{- if .Values.persistentVolume.accessModes }}
  {{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
  {{- end }}
  {{- else }}
  {{ print "- ReadWriteOnce" }}
  {{- end }}
  hostPath: 
    path: {{ .Values.persistentVolume.hostPath.path}}