{{- $name := include "persistent-layer.name" . -}}
{{- $selectorLabels := include "persistent-layer.selectorLabels" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}-statefulSet
spec:
  serviceName: {{ $name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ $selectorLabels | nindent 6 }}
  template:
    metadata:
      labels: {{ $selectorLabels | nindent 8 }}
    spec:
      containers:
        - name: "{{ $name }}-container"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}" 
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent"}}
          ports:
            - containerPort: {{ .Values.statefulSet.containerPort | default 5432}}
          envFrom:
            - configMapRef:
              name: {{ $name }}-config
          env:
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $name }}-secret
                  key: POSTGRESS_PASSWORD
          
