# Default values for rest-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/software-containerization-vu/sc-helm/rest-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
port: 8000
service:
  nodePort: 30007
  targetPort: 8000
  type: ClusterIP
  clusterIPNone: true

hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilizationPercentate: 60

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
